---
# tasks file for AnsibleUserCreation

- name : Create Group
  group :
    name: '{{ group_name }}'
    state: present

- name : Create Ansible User
  user :
    name: '{{ ansible_user_id }}'
    #password: <If needed Encrypted password to be added here>
    shell: /bin/bash
    group: '{{ group_name }}' 

- name : Add Ansible user to sudoers file
  copy:
    dest: "/etc/sudoers.d/'{{ ansible_user_id }}'"
    content: "'{{ ansible_user_id }}'        ALL=(ALL)       NOPASSWD: ALL"

- name : Copy ssh keys to authorized_keys file
  authorized_key:
    user: '{{ ansible_user_id }}'
    key: "{{ lookup('file', '/home/''{{ ansible_user_id }}''/.ssh/id_rsa.pub') }}"
    state: present
